/**
 * World landmass as a packed bitmask, 640 x 320 cells in equirectangular
 * projection. Generated from Natural Earth land-50m (public domain) by
 * rasterising the coastline polygons at 5120x2560 and sampling each cell, so
 * coastlines, islands and inland seas resolve at real-map fidelity.
 *
 * Packed one bit per cell, MSB first, then base64: ~34 KB, against ~205 KB as
 * plain text or 545 KB for the source polygons.
 */
export const LAND_COLS = 640;
export const LAND_ROWS = 320;
export const LAND_MASK =
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////oAAAAH//////8AAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3/////+AHJ+///////4AAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////H///////' +
    '////5B/AAAAAAAAAAAAAAAAAAAABwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj/////' +
    '//D//////////////+AAAAAAAAAAAAAAAAAAAD8AMAAAAAAAwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAH/z/////+P//////////////+AAAAAAAAAAAAAAAAAH/w/f/gAAAIAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAw//+////+D//////////////+AAAAAAAAAA//8AwAAAHucfQAAAAAAAAD/9gAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAB//////9AA/////////////8AAAAAAAAH2+f/gAAAAAAAAAAAAABwAAAD//AAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AA//7//+AH//////////////wAAAAAAAAH//gAAAAAAAAAAAAAAAAAAAAA/9/A' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwH/n4f////4f//////////////4AAAAAAAABvf7wAAAAAAAAAAAAAA' +
    'AAAAAAAAf+QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+BA3H8Ae//+B///////////////4AAAAAAAAAP+D8AAA' +
    'AAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+DgDAAAA4//+AE///////////////4AAAAA' +
    'AAAAfgTAAAAAAAAAAAAAAAAAAAIAEA/zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/zAYDHp/d///8AC//////////' +
    '////5gAAAAAAAAAMAAAAAAAAAAAAAAfgAAAAAAAAH/7/AAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAB/t/DyP/49+AgPAA' +
    'B/7////////////6AAAAAAAAAAAAAAAAAAAAAAAf/4AAAAAAA+P////AAAAAAAcQAAEAAAAAAAAAAAAAAAAAAAAAAAAAnf//' +
    '+P/7j/3/gAAAAAH///////////wAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAH//////8AAAAAAT//IAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAB+//zB8/P///gAAAAAH//////////64AAAAAAAAAAAAAAAAAAAAAf+AAAAAAAf///////wAAAAAAP/4/wAAAAAAAA' +
    'AAAAAAAAAAAAAAAAP8AH4AAAIAGf/4AAAAAAH//////////8AAAAAAAAAABAAAAAAAAAAD+AAAAAAAJ///////+AAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAA/h/geAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAP//////' +
    '3IAABAAAQHwAAAAAAAAAAAAAAAAAAAAAAAAAAD//+AC8H+P8P///AAAAAAf/////////4AAAAAAAAAAAAAAAAAAAAAH8AAAO' +
    'AwH///////z//+Af+AAAvgAAAAAAAAAAAAAAAAAAAAAAAAAAf//73Ph/4/h9/78AAAAAD/////////+AAAAAAAAAAAAAAAAA' +
    'AAAAB/AAAB+MDf/////////////8AAA+AAAAAAAAAAAAAAAAAAAAAAAAAAD/9//++B/zwP7//+AAAAAH/////////4AAAAAA' +
    'AAAAAAAAAAAAAAAP4AAAP4Z+//////////////wAAf//wAAAAAAAAMAAAAAAAAAAAAAAAD/P///8A/PA////+wAAAAf/////' +
    '////gAAAAAAAAAAAAAAAAAAAAB/gAAB/vf///////////////Bhu///gAAAAAAAAf//////////////////////////////+' +
    '/////////////f////////////////////////////////////////////////////////////8AAAAAP///AAAAAAgAAf//' +
    '/8QH8H/////+AAAB////////58AAAAAAAAAAAAH//gAAAAAAdIAB/4//9//////////////////////wAAAAAAAAAAH/////' +
    '4AAD/iAB////+A/4Bf/z//+AAAP/////////AAAAAAAAAAAAf//8QAAAAAAA4AH/n/////////////////////////AAOf+A' +
    'AAAAA///////wf////D////gfv4A/Er//4AAAff///////wAAAAAAAAAAAv////4AAADgAAf4f+f////////////////////' +
    '///////p//x///+P///////z/////F//7//7//////////////////////////////////////+////+/3/5//z/////////' +
    '/////////////////////x///4AAAAAAAAAAAAAAD/73/9+BHwf//AB////4AAAAA3/////////////+AAAAAA/+P/fAQABA' +
    'OGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAAAAAf5wB/5AAeA/4+AB////wAAAAH/////////////+AAAAAA' +
    'AP7+AAAAAAB4cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAAAAAABgAAGAAgB//8AB///AAAAAA//////////' +
    '////wAAAAAAAfvgAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABh///gAAAAAAAAAAAAAAAAAAQAAy///ACAf/+AAAAA' +
    'P/////////////8AAAAAPgD+AAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAB/j4AAAAAAAAAAAAAAAAAAAAKB///w' +
    'A/h//4AAAAj///9/5////////wAAAAAH/8YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+B/4AAAAAAAAAAAAAAAAA' +
    'AAAAAHb///gB8f//8AAA/////7AD///////8AAP4AAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7/v//////' +
    '///////////////////////9//////9//////////////////////v//////////////////////////////////////////' +
    'ADgAJn/////////////////////z/gen//AAAB///wAAAAB//AAAAAAAP//8P///P///////////////////////////////' +
    '//////////AAAAAAP////////////////////wfngAH/+AAAD///AAAAAP/gAAAAAAB///j/////////////////////////' +
    '/////////////////////AAAcAv////////////////////+AMANAP74AAAH//4AAAAAAAAAAAAAB///x///////////////' +
    '///////////////////////////////+AAAAH/////////////////////QAHAIQf8gAAAP//AAAAAAAAAAAAAAf//8H////' +
    '//////////////////////////////////////////4AAAB/////////////////////4AAYZ/4D4AAAAf/4AAAAAAAAABgA' +
    'AH///gP/////////////////////////////////////////3///gAAAAP/////////////////////AAAAD/4AYAAAA//gA' +
    'AAAAAAAAEAAAf//+A////////////////////////////////////////g/f//gAAAAAP///7////////////////4AAAAf/' +
    '+AAAAAA/8AAAAAAAAAAAAAD///4D///////////////////////////////////////8Dh//wAAACAG////f9///////////' +
    '////AAAAA//zCAAAAAPwAAAAAAAAAAAEAP///5H/3/////////////////////////////////////AA/+cAAAAAAY7//71A' +
    'D/////////////8AAABD//AMAAAAAGAAAAAAAAAAAAAAf///yGA/////////////////////////////////////4APlAgAA' +
    'AAAAAP/8MAAA/////////////wAAAAf/+B4AAAAAAAAAAAAAAAAAIAB///+AP///////////////////////////////////' +
    '/4fwD8gAAAAAAAAA3/4AAAAf////////////wAAAD//+PwAAAAAAAAAAAAAAAABgAD+P/gC/////////////////////////' +
    '//////////AABAAfmAAAAAAAAAAA/cAAAAf////////////gAAAD////gAAAAAAAAAAAAAAAG8AAHg/8Ab//////////////' +
    '////////////////////wAAAAH8AAAAAAAAAAAHnwAAAA/////////////AAAAH////AAAAAAAAAAAAAAAA7+AAAZ/zDn///' +
    '//////////////////////////////+AAAAB/8AAAAAAAAAAA8cAAAAD/////////////4AAAP///+AAAAAAAAAAAAAAAAfw' +
    'AAHj/IP//////////////////////////////////gAAAAP/wAAAAAAAAAAeAAAAAAD/////////////8AAQ////4AAAAAAA' +
    'AAAAAAAAB+AAA/H8B//////////////////////////////////8AAAAB//AAAAAAAAAAPwAAAAAAD/////////////8AGH/' +
    '///4AAAAAAAAAAAAAAAP8AAD78AH//////////////////////////////////AAAAAP/0AAAAAAAAAD4AAAAAAAP///////' +
    '///////wB/////wAAAAAAAAAAAAAAA/4AAHtgAf/////////////////////////////////wAAAAA//AAAAAAAAAB0AAAAA' +
    'AAAf//////////////w//////4AAAAAAAAAAAAAA/fwAAdwDn/////////////////////////////////+YAAAAD/8BQAAA' +
    'AAAAQAAAAAAAABD//////////////B//////wAAAAAAAAAAAAAP9PwAB9x///////////////////////////////////+uE' +
    'AAAH+AAAAAAAAAGAAAAAAAAAHP/////////////8H//////wAAAAAAAAAAAAA/g/AAX/////////////////////////////' +
    '/////////8QAAAfwAAAAAAAACAAAAAAAAAAMf/////////////8f//////gAAAAAAAAAAAAB+P+A////////////////////' +
    '////////////////////7gAAB/AAABAAAAAAAAAAAAAAAAY//////////////g//////+AAAAAAAAAAAAAP4f+D/////////' +
    '///////////////////////////////uAAADwAAACAAQQAAAAAAAAAAAAA//////////////L//////4AAAAAAAAAAAAA+H/' +
    '4f////////////////////////////////////////4AAAPAAAAAEQAAAAAAAAAAAAAAD/////////////+///////gAAAAA' +
    'AAAAAAABAH/H////////////////////////////////////////7gAAAwAAAAACAAAAAAAAAAAAAAAP////////////////' +
    '///+OAAAAAAAAAAAAAAA/9/////////////////////////////////////////PAAAIAAAAAAAAAAAAAAAAAAAAAA//////' +
    '//////////////xwAAAAAAAAAAAAAAPAP////////////////////////////////////////88AAAgAAAAAAAAAAAAAAAAA' +
    'AAAAA/////////////////+HgHkAAAAAAAAAAAAAAAT/////////////////////////////////////////zwAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAA9////////////////3nA/4AAAAAAAAAAAAAAD//////////////////////////////////////////P' +
    'gAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////7/AH/wAAAAAAAAAAAAAD/////////////////////////////////' +
    '/////////4wAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////4A//AAAAAAAAAAAAAAf//////////////////////' +
    '////////////////////DAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////////ghd+AAAAAAAAAAAAAAP///////////' +
    '//////////////////////////////4MAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////////////+AgNwAAAAAAAAAAAAAAP' +
    '///////////v/////////////////////////////A4AAgAAAAAAAAAAAAAAAAAAAAAAAB/////////////////72AAAAAAA' +
    'AAAAAAAAAAf////////+/h///wP////////////////////////8CAAAAAAAAAAAAAAAAAAAAAAAAAAAH///////////////' +
    '//98AAAAAAAAAAAAAAAAA/////////wcH//+A/////////////////////////gIACAAAAAAAAAAAAAAAAAAAAAAAAAf////' +
    '/////////////+AAAAAAAAAAAAAAAAAD///8////+D////Af////////////////////////8BgDgAAAAAAAAAAAAAAAAAAA' +
    'AAAAAB////////////////+fgAAAAAAAAAAAAAAAAAP///x////gHD//4H/////////////////////////gDAQAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAH///////////////+DgAAAAAAAAAAAAAAAAAB//+fj///+AAB//wP////////////////////////4AP' +
    '0AAAAAAAAAAAAAAAAAAAAAAAAAAf///////////////gEAAAAAAAAAAAAAAAAH/H//g/D///4AAD//gf////////////////' +
    '////////AB/AAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAB///8ID+H///AAAD/+A//////' +
    '//////////////////4Af8AAAAAAAAAAAAAAAAAAAAAAAAAAH///////////////wAAAAAAAAAAAAAAAAAD///wBn8D//4AA' +
    'AD/8B///////////////////////gAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAf///////////////wAAAAAAAAAAAAAAAAAP//' +
    '/AGH+D//wH4AP/4E//////////////////////4AAGIAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////////5AAAAAAAAAA' +
    'AAAAAAAA///wAIH8P//8/8D//gD//////////////////////gAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////////////+' +
    'AAAAAAAAAAAAAAAAAAD//8ADgH8/95//////A////////////////////n/+AABwAAAAAAAAAAAAAAAAAAAAAAAAAAAf////' +
    '//////////gAAAAAAAAAAAAAAAAAAP//gAGAPb9n//////+H///////////////////8f/gAAHAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAA//////////////8AAAAAAAAAAAAIAAAAAB//8MAYAMH4P//////wP///////////////////Dn4AAAeAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAD//////////////AAAAAAAAAAAAAAAAAAAH//yABgA4P0///////A///////////////////8YPgAADw' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////+AAAAAAAAAAAAAEAAAAAf//AAAADA/j//////4B////////////////' +
    '//+AA/gAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////////wAAAAAAAAAAAAAAgAAAA//4AAAPoB/H//////gH/////' +
    '//////////////ID+AAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////+AAAAAAAAAAAAAAAAAAAD/+AAAgeADwP//' +
    '////gP//////////////////98B8ABPgAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////4AAAAAAAAAAAAAAAAAAAA/w' +
    'B7/0YAOA///////n////////////////////wPwAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////gAAAAAAAAAAA' +
    'AAAAAAAABgD//+AAAIBMef////////////////////////4AfAg/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////+A' +
    'AAAAAAAAAAAAAAAAAAAGA///8AAAAIAB////////////////////////+AB8Af/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///' +
    '/////////wAAAAAAAAAAAAAAAAAAAAf////wAAA+AHj////////////////////////wAPwf/8AAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAB////////////+AAAAAAAAAAAAAAAAAAAAD////+AAAAAAIP////////////////////////gA4H7sAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAC////////////wAAAAAAAAAAAAAAAAAAAAf////wAAAAAAB/////////////////////////AAA78AA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////8AAAAAAAAAAAAAAAAAAAAH/////wAAAAAAP/////////////////////' +
    '///+AMPeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////gAAAAAAAAAAAAAAAAAEAA//////+ABwAAA///////////' +
    '//////////////4AB/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////4AAAAAAAAAAAAAAAAAAAAH//////+APwAAD' +
    '/////////////////////////wABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAf//' +
    '////8B/4AAf/////////////////////////gAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc/////////8AAAAAAAAAAAAA' +
    'AAAAAAAD///////+H//n//////////////////////////+AAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABx/////////gAA' +
    'AAAAAAAAAAAAAAAAAAP///////+f/////////////////////////////wAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADn/' +
    '/////8D/AAAAAAAAAAAAAAAAAAAAA/////////////////7/////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAHv////8XgA8AAAAAAAAAAAAAAAAAAAAD////////////////+D////////////////////+AAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAQO/////gBAB4AAAAAAAAAAAAAAAAAAAQ/////////////f///8P////////////////////wAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd////4AAAHgAAAAAAAAAAAAAAAAAAhH/////////////////wf////////////////' +
    '////AAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHx///+AAAA+AAAAAAAAAAAAAAAAAAAh/////////////+f///h//////' +
    '//////////////4ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPn///4AAAB8AAAAAAAAAAAAAAAAAAAP/////////////x' +
    '////A////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPH///gAAADzgAAAAAAAAAAAAAAAAAB////' +
    '//////////j///+B9//////////////////8ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMf//+AAAAPCAAAAAAAAAAAA' +
    'AAAAAAP/////////////+H///8AX//////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4///4AAAAYAA' +
    'AAAAAAAAAAAAAAAAA//////////////8f///8BH/////////////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADx' +
    '///gAAAABIAAAAAAAAAAAAAAAAAH//////////////w////wcAAD///////////////xgAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAGD//+AAAAAEQAAAAAAAAAAAAAAAAAf//////////////j////B4AAH//////////////8OIAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAGD//wAAAAAQQAAAAAAAAAAAAAAAAH//////////////+D/////4AAP//////////////hwAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMP//AAAAAAAAAAAAAAAAAAAAAAAAf//////////////4P/////4AAP///////////' +
    '//8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAD/gCAAAAAAAAAAAAAAAAB///////////////wf/////wAAX' +
    '/////////////AcAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAA//wAAAM/wCAAAAAAAAAAAAAAAAP///////////////' +
    'h//////AAD//////3//////AAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//gADAIPgEAAAAAAAAAAAAAAAA/////' +
    '///////////H/////8AAH/////Yf/////4AAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAH/+AB/AAPxAAAAAAAAAAA' +
    'AAAAAD///////////////8f/////gAAPf///4B////4YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AH8AAHw' +
    'AAAAAAAAAAAAAAAAP///////////////w/////+AAAB////gD////BgAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAA' +
    'D//4AfgAA/bAAAAAAAAAAAAAAAAf///////////////A/////gAAAH///8AH///4OAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAA' +
    'AAAAAAAAAAAH//gD8AAAA/gAAAAAAAAAAAAAAD///////////////8B////+AAAAf//+AAP///B4AAEAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAH//g/wAAAD/AAAAAAAAAAAAAAAH///////////////4H////wAAAB///4AA///8HgAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////AADw/08AAAAAAAAAAAAAAf///////////////wf///+AAAAH///AAA///4' +
    'IAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///4AACAAAAAAAAAAAAAAAAAB////////////////g////gAAAA' +
    'P//wAAD///gAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAACAAAAAAAAAABAAH///////////////' +
    '/B///8AAAAA//+AAAP///AAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//+AAAAAAAAAAAAAAAAAACAA/////' +
    '///////////8L//+AAAAAD//wAAB9///AAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5/wcAAAAAAIAAAAAAA' +
    'AAABAD////////////////wP//gAAAAAP/8AAAHH//+AAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//8AAA' +
    'AAAgAAAAAAAAAAAAP////////////////g//8AAAAAAf/gAAAAP//8AABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAH//wAAAAABAAAAAAAAAACAB/////////////////j//AAAAAAB/+AAAAA///wAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAD/////////////////P/gAAAAAAD/4AAAAD///AAAPgAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAQAAAAAAAAAAAAP////////////////+f4AAAAAAAP/gAAAAP//8AAA3gAAAAA' +
    'QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAAAAAAAAA/////////////////94AAAAAAAAf+AAAEAd//' +
    '4AADEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAD/////////////////+AAGAAAAA' +
    'B/4AAAAD3//AAAEeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAB0gAgAAAAAAAAAAAAH///////////////' +
    '//gAIAAAAAAH/AAACAHD/8AABA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAMcAAAAAAAAAAAAAAAf////' +
    '////////////+ADgAAAAAAP8AAAAAYH/wAAAZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAP/4SEAAAAAAA' +
    'AAAAAAf////////////////8X+AAAAAAAfwAAAADgf+AAAh8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AB/' +
    '/+ewAAAAAAAAAAAAA///////////////////4AAAAAAB/AAAAAGA/gAAGDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAD4AH9//+AAAAAAAAAAAAAB///////////////////gAAAAAAH6AAAAAwA8AAAgfAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAADx4////8AAAAAAAAAAAAAD//////////////////8AAAAAAAPMAAAABwDgAAGAxgAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAH8/////oAAAAAAAAAAAAAP//////////////////wAAAAAAA44AAAAPAIAAAwBeAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALh/////4AAAAAAAAAAAAAf/////////////////+AAAAAAABDgAAEA+AA' +
    'AACAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPH/////wAAAAAAAAAAAAB//////////////////4AAAAAA' +
    'AAPAAAAA4AAAAAB/gAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////AAAAAAAAAAAAAB//////////////' +
    '////AAAAAAAAA8AAAgBwAAABAI+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////AAAAAAAAAAAAAD///' +
    '//////////////4AAAAAAAADgAAAADgAAAGAjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////8AAAAA' +
    'AAAAAAAD///Af////////////gAAAAAAAAEAAABAPAAAA+EGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/' +
    '/////8AAAAAAAAAAAAH//gB////////////8AAAAAAAAAAAAAHg/AAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAA///////8AAAAAAAAAAAAPgIAD////////////wAAAAAAAAAAAAAfB8AAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAD///////4AAAAAAAAAAAAAAAAAP//////////+AAAAAAAAAAAAAA+HwCAP8AAQAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////gAAAAAAAAAAAAAAAABf//////////wAAAAAAAAAAAAAA8fAIB/gAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAB//////////+AAAAAAAAAAAAAAB88A' +
    'Qf+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////8AAAAAAAAAAAAAAAAAH//////////wAAAAAAA' +
    'AAAAAAA3x4AD/8AACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////4AAAAAAAAAAAAAAAAAf///////' +
    '//+AAAAAAAAAAAAAAAH7gCf/wAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////gAAAAAAAAAAAAAA' +
    'AAB//////////gAAAAAAAAAAAAAADfyAP//hBjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////+AAAA' +
    'AAAAAAAAAAAAAH/////////8AAAAAAAAAAAAAAAE/wB//+f8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAH//' +
    '//////8AAAAAAAAAAAAAAAAQ//////////gAAAAAAAAAAAAAAAD/gD//hBgYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAABgAAf////////8AAAAAAAAAAAAAAAAD/////////8AAAAAAAAAAAAAAAAH/AP/+EgDDQAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAGgAD/////////+AAAAAAAAAAAAAAAAf/////////gAAAAAAAAAAAAAAABP4A//4zwAP5AAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////////+AAAAAAAAAAAAAAAA/////////8AAAAAAAAAAAAAAAAE/0F//D/AwfgAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////+AAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAAAB/Y' +
    'H/4PBwE+PwAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////AAAAAAAAAAAAAAAH////////8AAAAAAAAA' +
    'AAAAAAAAX/0P/h+AAA8/4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////8AAAAAAAAAAAAAAP///////' +
    '/wAAAAAAAAAAAAAAAAAv/Qf+HcDfH3/8AAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////8AAAAAAAAAAA' +
    'AAAf///////+AAAAAAAAAAAAAAAAAAfwAB4NwNGL//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////////4' +
    'AAAAAAAAAAAAAA////////4AAAAAAAAAAAAAAAAAA/AAAAzgAAH//8AHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//' +
    '//////////wAAAAAAAAAAAAAB////////gAAAAAAAAAAAAAAAAAB8AAADOAAAD//8AYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAA/////////////4AAAAAAAAAAAAAH///////+AAAAAAAAAAAAAAAAAARwAAAM4AAIB//0vgAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAH/////////////wAAAAAAAAAAAAAP///////wAAAAAAAAAAAAAAAAAAA4AAAAAAAMD//z4EAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////////////AAAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAAAD4QAAAAAAgP/' +
    '/gAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////8AAAAAAAAAAAAAB///////8AAAAAAAAAAAAAAAAAAAH' +
    '/+ACAAAgA//8AAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////wAAAAAAAAAAAAAH///////wAAAAAAAAA' +
    'AAAAAAAAAAH/4AAAgEAH//wAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////AAAAAAAAAAAAAAf//////' +
    '/AAAAAAAAAAAAAAAAAAAAA/+Yj8QgAb+HwABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////////////8AAAAAAAAAA' +
    'AAAB///////8AAAAAAAAAAAAAAAAAAAAABv3w8AAAD4PAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////////' +
    'gAAAAAAAAAAAAAH///////4AAAAAAAAAAAAAAAAAAAAAAAgOAAAAHAeRABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/' +
    '//////////8AAAAAAAAAAAAAAf///////gAAAAAAAAAAAAAAAAAAAAAADhwAAAAAA+gADAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAB////////////wAAAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAMAABAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAD///////////8AAAAAAAAAAAAAAD///////8AAAAAAAAAAAAAAAAAAAAAAAAgABAADAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////wAAAAAAAAAAAAAAP///////wAAAAAAAAAAAAAAAAAAAAAAAAAB2CAM' +
    'AACACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////////+AAAAAAAAAAAAAAA////////AAEAAAAAAAAAAAAAAAAA' +
    'AAAAAAB/4A4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///////////wAAAAAAAAAAAAAAH///////8AAQAAAAAA' +
    'AAAAAAAAAAAAAAAAAP/gDgAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////+AAAAAAAAAAAAAAA///////' +
    '/wAHgAAAAAAAAAAAAAAAAAAAAAAB/+AeAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////4AAAAAAAAAAA' +
    'AAAD////////AAeAAAAAAAAAAAAAAAAAAAAAAEP/8B4AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////g' +
    'AAAAAAAAAAAAAAP///////8AB4AAAAAAAAAAAAAAAAAAAAAD4/+AH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/' +
    '/////////+AAAAAAAAAAAAAAB////////4APwAAAAAAAAAAAAAAAAAAAAAP//4AfwAAAAACAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAD//////////4AAAAAAAAAAAAAAH////////AD/AAAAAAAAAAAAAAAAAAAAAB///0B/AAAAAAKAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAD//////////gAAAAAAAAAAAAAAf///////4B/4AAAAAAAAAAAAAAAAAAAAAH///4H+AAAAAAQAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////+AAAAAAAAAAAAAAB////////gH/gAAAAAAAAAAAAAAAAAAAAD////0f' +
    '4AAAAAAAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////wAAAAAAAAAAAAAAH///////4A/8AAAAAAAAAAAAAAAAA' +
    'AAAAf////z/wAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAH/////////AAAAAAAAAAAAAAAf//////+AD/wAAAAAA' +
    'AAAAAAAAAAAAAAB///////AAAAAAEAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////8AAAAAAAAAAAAAAB///////' +
    'gAP/AAAAAAAAAAAAAAAAAAAAAH//////8AAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////////wAAAAAAAAAAA' +
    'AAAD//////+AA/8AAAAAAAAAAAAAAAAAAAAA///////wAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////A' +
    'AAAAAAAAAAAAAAP//////gAB/gAAAAAAAAAAAAAAAAAAAAH///////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'H////////4AAAAAAAAAAAAAAAf/////8AAH+AAIAAAAAAAAAAAAAAAAAH////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAf////////AAAAAAAAAAAAAAAB//////wAA/4AAgAAAAAAAAAAAAAAAAF/////////gAAACAAAAACAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAB////////4AAAAAAAAAAAAAAAD//////gAD/AAgAAAAAAAAAAAAAAAAA/////////+AAAAEQAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////gAAAAAAAAAAAAAAAP/////+AAf8AAAAAAAAAAAAAAAAAAAP////////' +
    '/8AAAAMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////+AAAAAAAAAAAAAAAAf/////4AB/wAAAAAAAAAAAAAAAAA' +
    'AD//////////8AAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////wAAAAAAAAAAAAAAAB//////gAH+AAAAAAA' +
    'AAAAAAAAAAAAP//////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////gAAAAAAAAAAAAAAAAH/////+' +
    'AAf4AAAAAAAAAAAAAAAAAAA///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////0AAAAAAAAAAAAA' +
    'AAAAf/////4AB/gAAAAAAAAAAAAAAAAAAH///////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////8AAA' +
    'AAAAAAAAAAAAAAA//////gAD8AAAAAAAAAAAAAAAAAAAf//////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'P//////gAAAAAAAAAAAAAAAAAD/////4AAPwAAAAAAAAAAAAAAAAAAA///////////6AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAP////+AAAIAAAAAAAAAAAAAAAAAAAP///////////wAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAD//////wAAAAAAAAAAAAAAAAAA/////4AAAAAAAAAAAAAAAAAAAAAAAf///////////AAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////AAAAAAAAAAAAAAAAAAB/////gAAAAAAAAAAAAAAAAAAAAAAA/////////' +
    '//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAH////8AAAAAAAAAAAAAAAAAAAAAA' +
    'AD///////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////wAAAAAAAAAAAAAAAAAAP////wAAAAAAAAAAA' +
    'AAAAAAAAAAAAH///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAAAAAAAAAAAAf////A' +
    'AAAAAAAAAAAAAAAAAAAAAAAf//////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//////wAAAAAAAAAAAAAA' +
    'AAAAB////4AAAAAAAAAAAAAAAAAAAAAAAA///////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////AAAA' +
    'AAAAAAAAAAAAAAAD////AAAAAAAAAAAAAAAAAAAAAAAAD///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'f/////4AAAAAAAAAAAAAAAAAAAP///4AAAAAAAAAAAAAAAAAAAAAAAAP//////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAD/////+AAAAAAAAAAAAAAAAAAAAf///AAAAAAAAAAAAAAAAAAAAAAAAA///////////wAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAP/////0AAAAAAAAAAAAAAAAAAAB///8AAAAAAAAAAAAAAAAAAAAAAAAB///////////AAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////gAAAAAAAAAAAAAAAAAAAD///AAAAAAAAAAAAAAAAAAAAAAAAAH///4P///' +
    '//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////4AAAAAAAAAAAAAAAAAAAAP//4AAAAAAAAAAAAAAAAAAAAAAA' +
    'AAf//8AD/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////gAAAAAAAAAAAAAAAAAAAB///AAAAAAAAAAAAA' +
    'AAAAAAAAAAAAB//8AAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////8AAAAAAAAAAAAAAAAAAAAD//4AA' +
    'AAAAAAAAAAAAAAAAAAAAAAAP//gAAff///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////gAAAAAAAAAAAAAAA' +
    'AAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAA/8QAAA7///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///78AAAAA' +
    'AAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAADL///wAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB' +
    '////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAABv///AAAAAAHAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAH////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHf//4AAAAAAOAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAA////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///gAAAAAAYA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/' +
    '/+AAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAH//4AAAAAADiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAf/4AAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////gAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHfAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAH+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///wAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH' +
    '//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAcAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjAAAAAAAxwAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAD+A' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'PwAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAA+AAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAB4AAAAAAfAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//gAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf' +
    '/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABf/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABf/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8AAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/' +
    '/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAL/gAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/wAAAAAAABwAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/0AAAAAAAB' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'DgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7/gAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'ACfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAX/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAAAAGA/wB+AAAAD8wAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAN+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAz/////+f/AA/w///8AAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAz//+gAAAAAAf/////////////////' +
    'gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////8AAB////////' +
    '///////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////////w' +
    'AB/////////////////////4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P4AAAAAAAAAAAAAAAAAAAAAAAAAAAA4' +
    'Af////////AAP//////////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7/8AAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAD4D////////4AH////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcPv/wAAAAAAA' +
    'AAAAAAAAAABgAAMIAAIA//////////+Af/////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4' +
    'ff/4AAAAAAAAAAAAAAAEIAX////HcH///////////+H//////////////////////////v+AAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAMf+//AAAAAAAAAAAAAAJziwf///////////////////wf////////////////////////////AAAAAAAAAAAAAA' +
    'AAAAAAAAAAAABMgAAAAAP/7/8AAAAAAAAAAAAAA///////////////////////+H/////////////////////////////wAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAf/AAAAAAD/H/wAAAAAAAAAAAAAF///////////////////////z//////////////////////' +
    '///////+AAAAAAAAAAAAAAAAAAAAAAAABPuAh+AAQHAD//gAAAAAAAAAAAAB///////////////////////+f///////////' +
    '//////////////////wAAAAAAAAAAAAAAAAAB4AAAAAAf////8H+f///8AAAAAAAAAAAAD//////////////////////////' +
    '////////////////////////////xAAAAAAAAAAAAAAAAAAB99mMAAB////////////wAAAAAAAAAAAwH///////////////' +
    '//////////////////////////////////////gAAAAAAAAAAAAAAAABDgwAf/xwAA////////////AAAAAAAAAAABD/////' +
    '////////////////////////////////////////////////3AAAAAAAAAAAAAAAAf////////8f4f//////////AAAAAAAA' +
    'AAAAAf////////////////////////////////////////////////////+AAAAAAAAAAAAAAA3/////////////////////' +
    '//wAAAAAAAAAAA///////////////////////////////////////////////////////8AAAAAAAAAAAAAD////////////' +
    '////////////AAAAAAAAAAAP////////////////////////////////////////////////////////wAAAAAAAAAAAAA8v' +
    '///////////////////+D+AAAAAAAAAAAP////////////////////////////////////////////////////////+AAAAA' +
    'AAAAAAP/8//////////////////////4AAAAAAAAAAAf////////////////////////////////////////////////////' +
    '/////+H4AAAAAAAAA/////////////////////////wAAAAAAH+AAH//////////////////////////////////////////' +
    '////////////////+MAAAAAAAAAAP/////////////////////f+AAeAAAAB/8AB////////////////////////////////' +
    '////////////////////////////gAAAAAAAD+AP/////////////////////gAAfAAAAAP/4AH/////////////////////' +
    '/////////////////////////////////////wAAAAAAAAAH+AAP/////////////////////4Dx4AgAB//wAAN/////////' +
    '///////////////////////////////////////////////4AAAAAAAAAAAAAA//////////////////////gABgPgD//+AA' +
    'AH////////////////////////////////////////////////////////gAAAAAAAAAAAAAAf/////////////////////7' +
    '4A78Af+AAAD//////////////////////////////////////////////////////////AAAAAAAAAAPwH//////////////' +
    '////////////4AAAAAAD///////////////////////////////////////////////////////////8AAAAAAAAAAAGB///' +
    '///////////////////////4AAAH/B/////////////////////////////////////////////////////////////AAAAA' +
    'AAAAAAAB///////////////////////////wD///////////////////////////////////////////////////////////' +
    '//////4AAAAAL+AHgP///////////////////////////+D/////////////////////////////////////////////////' +
    '/////////////////+AAAAAAH///////////////////////////////////////////////////////////////////////' +
    '//////////////////////////////AAAAAAH///////////////////////////////////////////////////////////' +
    '//////////////////////////////////////////4AAf///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';

export type LandCell = {
  /** Map-space position, 0..1. */
  u: number;
  v: number;
  /** True longitude/latitude in radians, for solar geometry. */
  lon: number;
  lat: number;
  /** 1 when the cell borders ocean — used to pick out coastlines. */
  edge: number;
};

/**
 * Decode the mask to cells, skipping Antarctica. A cell is marked as coastal
 * when any of its four neighbours is water, which is what lets the renderer
 * draw shorelines brighter than continental interiors.
 */
export function landCells(minLat = -58, maxLat = 76): LandCell[] {
  const bin = typeof atob === 'function' ? atob(LAND_MASK) : '';
  const at = (c: number, r: number) => {
    if (c < 0 || r < 0 || c >= LAND_COLS || r >= LAND_ROWS) return 0;
    const i = r * LAND_COLS + c;
    return bin.charCodeAt(i >> 3) & (128 >> (i & 7)) ? 1 : 0;
  };

  const out: LandCell[] = [];
  const D = Math.PI / 180;
  for (let r = 0; r < LAND_ROWS; r++) {
    const v = (r + 0.5) / LAND_ROWS;
    const lat = 90 - v * 180;
    if (lat < minLat || lat > maxLat) continue;

    /*
     * Equirectangular spaces cells evenly in longitude, but a degree of
     * longitude covers cos(lat) as much ground near the poles as at the
     * equator. Left alone, northern Canada and Siberia render as a solid bar.
     * Keeping cells with probability cos(lat) restores constant density per
     * unit area — the same correction a dot-density map applies.
     */
    const keep = Math.cos(lat * D);

    for (let c = 0; c < LAND_COLS; c++) {
      if (!at(c, r)) continue;
      // Deterministic hash, so thinning is stable across renders.
      const h = (((c * 73856093) ^ (r * 19349663)) >>> 0) % 10000;
      if (h / 10000 > keep) continue;

      const u = (c + 0.5) / LAND_COLS;
      const edge =
        at(c - 1, r) && at(c + 1, r) && at(c, r - 1) && at(c, r + 1) ? 0 : 1;
      out.push({ u, v, lon: (u * 360 - 180) * D, lat: lat * D, edge });
    }
  }
  return out;
}
